// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 31 11:22:35 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showenrolledstuds_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class showEnrolledStuds_WSDHelper
  {
  public static IshowEnrolledStuds_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/Desktop/ccrepository/unterordner/workspace82/CampusConnect_HK/src/com/webmethods/caf/is/wsclient/campusconnect/work/enrollment/showenrolledstuds_wsd/showEnrolledStuds_WSD.wsdl" );
    }

  public static IshowEnrolledStuds_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IshowEnrolledStuds_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IshowEnrolledStuds_WSD_PortType) Registry.bind( url, IshowEnrolledStuds_WSD_PortType.class, context );
    }
  }
