// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 31 11:22:35 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showenrolledstuds_wsd;

public class showEnrolledStuds implements java.io.Serializable
  {
  }
