// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 05:10:21 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1;

public interface IsavePersonalDataStud_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1.savePersonalDataStudResponse savePersonalDataStud( com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1.savePersonalDataStud savePersonalDataStud );
  }
