// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 05:10:21 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1;

public class savePersonalDataStud implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1.studInfo studInfo = new com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1.studInfo();

public com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1.studInfo getStudInfo()
    {
    return studInfo;
    }

  public void setStudInfo( com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1.studInfo value )
    {
    this.studInfo = value;
    }
  }
