// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 05:10:21 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastud_wsd_hk1;

public class studInfo implements java.io.Serializable
  {
  private java.lang.String addressLine1;
  private java.lang.String addressLine2;
  private java.lang.String studId;

  public java.lang.String getAddressLine1()
    {
    return addressLine1;
    }

  public void setAddressLine1( java.lang.String value )
    {
    this.addressLine1 = value;
    }

  public java.lang.String getAddressLine2()
    {
    return addressLine2;
    }

  public void setAddressLine2( java.lang.String value )
    {
    this.addressLine2 = value;
    }

  public java.lang.String getStudId()
    {
    return studId;
    }

  public void setStudId( java.lang.String value )
    {
    this.studId = value;
    }
  }
