// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:42:25 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1;

public class enrollment implements java.io.Serializable
  {
  private java.lang.String completed;
  private java.lang.String payed;
  private java.lang.String scoringresult;

  public java.lang.String getCompleted()
    {
    return completed;
    }

  public void setCompleted( java.lang.String value )
    {
    this.completed = value;
    }

  public java.lang.String getPayed()
    {
    return payed;
    }

  public void setPayed( java.lang.String value )
    {
    this.payed = value;
    }

  public java.lang.String getScoringresult()
    {
    return scoringresult;
    }

  public void setScoringresult( java.lang.String value )
    {
    this.scoringresult = value;
    }
  }
