// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:42:25 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1;

public interface IshowApplicantList_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.showApplicantsListResponse showApplicantsList( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.showApplicantsList showApplicantsList );
  }
