// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:42:25 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1;

public class showApplicantsListResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.student[] students;

  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.student[] getStudents()
    {
    return students;
    }

  public void setStudents( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.student[] value )
    {
    this.students = value;
    }
  }
