// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:42:25 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1;

public class student implements java.io.Serializable
  {
  private java.lang.String _FIRSTNAME;
  private java.lang.String _LASTNAME;
  private java.lang.String _REGISTERED;
  private java.math.BigDecimal _ACTIVE;
  private java.lang.String id;
private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.enrollment enrollment = new com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.enrollment();

  public java.lang.String get_FIRSTNAME()
    {
    return _FIRSTNAME;
    }

  public void set_FIRSTNAME( java.lang.String value )
    {
    this._FIRSTNAME = value;
    }

  public java.lang.String get_LASTNAME()
    {
    return _LASTNAME;
    }

  public void set_LASTNAME( java.lang.String value )
    {
    this._LASTNAME = value;
    }

  public java.lang.String get_REGISTERED()
    {
    return _REGISTERED;
    }

  public void set_REGISTERED( java.lang.String value )
    {
    this._REGISTERED = value;
    }

  public java.math.BigDecimal get_ACTIVE()
    {
    return _ACTIVE;
    }

  public void set_ACTIVE( java.math.BigDecimal value )
    {
    this._ACTIVE = value;
    }

  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.enrollment getEnrollment()
    {
    return enrollment;
    }

  public void setEnrollment( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1.enrollment value )
    {
    this.enrollment = value;
    }

  public java.lang.String getId()
    {
    return id;
    }

  public void setId( java.lang.String value )
    {
    this.id = value;
    }
  }
