// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Jan 11 15:44:55 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd_5;

public interface IsearchCourse_WSD_5_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd_5.searchCourseResponse searchCourse( com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd_5.searchCourse searchCourse );
  }
