// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Jan 11 15:44:55 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd_5;

public class searchCourseResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd_5.course[] courses;

  public com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd_5.course[] getCourses()
    {
    return courses;
    }

  public void setCourses( com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd_5.course[] value )
    {
    this.courses = value;
    }
  }
