// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 10 10:48:59 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd;

public interface IshowPersonalDateProf_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd.showPersonalDataProfResponse showPersonalDataProf( com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd.showPersonalDataProf showPersonalDataProf );
  }
