// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 10 10:48:59 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd;

public class profInfo implements java.io.Serializable
  {
  private java.lang.String firstName;
  private java.lang.String lastName;
  private java.lang.String title;
  private java.lang.String chair;
  private java.lang.String profId;

  public java.lang.String getFirstName()
    {
    return firstName;
    }

  public void setFirstName( java.lang.String value )
    {
    this.firstName = value;
    }

  public java.lang.String getLastName()
    {
    return lastName;
    }

  public void setLastName( java.lang.String value )
    {
    this.lastName = value;
    }

  public java.lang.String getTitle()
    {
    return title;
    }

  public void setTitle( java.lang.String value )
    {
    this.title = value;
    }

  public java.lang.String getChair()
    {
    return chair;
    }

  public void setChair( java.lang.String value )
    {
    this.chair = value;
    }

  public java.lang.String getProfId()
    {
    return profId;
    }

  public void setProfId( java.lang.String value )
    {
    this.profId = value;
    }
  }
