// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 10 10:48:59 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd;

public class showPersonalDataProf implements java.io.Serializable
  {
  private java.math.BigDecimal profId;

  public java.math.BigDecimal getProfId()
    {
    return profId;
    }

  public void setProfId( java.math.BigDecimal value )
    {
    this.profId = value;
    }
  }
