// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 10 10:48:59 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd;

public class showPersonalDataProfResponse implements java.io.Serializable
  {
  private java.lang.String outputMessage;
private com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd.profInfo profInfo = new com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd.profInfo();
  public java.lang.String getOutputMessage()
    {
    return outputMessage;
    }

  public void setOutputMessage( java.lang.String value )
    {
    this.outputMessage = value;
    }

  public com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd.profInfo getProfInfo()
    {
    return profInfo;
    }

  public void setProfInfo( com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldataprof.showpersonaldateprof_wsd.profInfo value )
    {
    this.profInfo = value;
    }
  }
