// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:57:47 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_hk1;

public interface IloadStudRegisteredCourses_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_hk1.loadStudRegisteredCoursesResponse loadStudRegisteredCourses( com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_hk1.loadStudRegisteredCourses loadStudRegisteredCourses );
  }
