// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:57:47 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_hk1;

public class loadStudRegisteredCoursesResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_hk1.course[] outCourses;
  private java.lang.String hidden;

  public com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_hk1.course[] getOutCourses()
    {
    return outCourses;
    }

  public void setOutCourses( com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_hk1.course[] value )
    {
    this.outCourses = value;
    }

  public java.lang.String getHidden()
    {
    return hidden;
    }

  public void setHidden( java.lang.String value )
    {
    this.hidden = value;
    }
  }
