// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:57:47 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_hk1;

public class loadStudRegisteredCourses implements java.io.Serializable
  {
  private java.lang.String studId;

  public java.lang.String getStudId()
    {
    return studId;
    }

  public void setStudId( java.lang.String value )
    {
    this.studId = value;
    }
  }
