// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:58:07 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2;

public interface IsaveStudInfos_WSD_HK2_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.saveStudInfosResponse saveStudInfos( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.saveStudInfos saveStudInfos );
  }
