// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:58:07 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2;

public class saveStudInfos implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.studDetails studDetails = new com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.studDetails();

public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.studDetails getStudDetails()
    {
    return studDetails;
    }

  public void setStudDetails( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.studDetails value )
    {
    this.studDetails = value;
    }
  }
