// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:58:07 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class saveStudInfos_WSD_HK2Helper
  {
  public static IsaveStudInfos_WSD_HK2_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/Desktop/ccrepository/unterordner/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/enrollment/savestudinfos_wsd_hk2/saveStudInfos_WSD_HK2.wsdl" );
    }

  public static IsaveStudInfos_WSD_HK2_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IsaveStudInfos_WSD_HK2_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IsaveStudInfos_WSD_HK2_PortType) Registry.bind( url, IsaveStudInfos_WSD_HK2_PortType.class, context );
    }
  }
