// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:58:07 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2;

public class studDetails implements java.io.Serializable
  {
  private java.lang.String _FIRSTNAME;
  private java.lang.String _LASTNAME;
  private java.lang.String _ADDRESSLINE1;
  private java.lang.String _ADDRESSLINE2;
  private java.lang.String _DEGREEPROGRAM;
  private java.lang.String _DOB;
  private java.lang.String _EMAIL;
  private java.lang.String _PHONE;
  private java.lang.String citizenship;
  private java.lang.String isenrolled;
  private java.lang.String entrancetest;
  private java.lang.String nc;
  private java.lang.String interview;
  private java.lang.String exmatriculated;
  private java.lang.String seconddegree;
  private java.lang.String datepregraduation;
  private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.document[] documents;

  public java.lang.String get_FIRSTNAME()
    {
    return _FIRSTNAME;
    }

  public void set_FIRSTNAME( java.lang.String value )
    {
    this._FIRSTNAME = value;
    }

  public java.lang.String get_LASTNAME()
    {
    return _LASTNAME;
    }

  public void set_LASTNAME( java.lang.String value )
    {
    this._LASTNAME = value;
    }

  public java.lang.String get_ADDRESSLINE1()
    {
    return _ADDRESSLINE1;
    }

  public void set_ADDRESSLINE1( java.lang.String value )
    {
    this._ADDRESSLINE1 = value;
    }

  public java.lang.String get_ADDRESSLINE2()
    {
    return _ADDRESSLINE2;
    }

  public void set_ADDRESSLINE2( java.lang.String value )
    {
    this._ADDRESSLINE2 = value;
    }

  public java.lang.String get_DEGREEPROGRAM()
    {
    return _DEGREEPROGRAM;
    }

  public void set_DEGREEPROGRAM( java.lang.String value )
    {
    this._DEGREEPROGRAM = value;
    }

  public java.lang.String get_DOB()
    {
    return _DOB;
    }

  public void set_DOB( java.lang.String value )
    {
    this._DOB = value;
    }

  public java.lang.String get_EMAIL()
    {
    return _EMAIL;
    }

  public void set_EMAIL( java.lang.String value )
    {
    this._EMAIL = value;
    }

  public java.lang.String get_PHONE()
    {
    return _PHONE;
    }

  public void set_PHONE( java.lang.String value )
    {
    this._PHONE = value;
    }

  public java.lang.String getCitizenship()
    {
    return citizenship;
    }

  public void setCitizenship( java.lang.String value )
    {
    this.citizenship = value;
    }

  public java.lang.String getIsenrolled()
    {
    return isenrolled;
    }

  public void setIsenrolled( java.lang.String value )
    {
    this.isenrolled = value;
    }

  public java.lang.String getEntrancetest()
    {
    return entrancetest;
    }

  public void setEntrancetest( java.lang.String value )
    {
    this.entrancetest = value;
    }

  public java.lang.String getNc()
    {
    return nc;
    }

  public void setNc( java.lang.String value )
    {
    this.nc = value;
    }

  public java.lang.String getInterview()
    {
    return interview;
    }

  public void setInterview( java.lang.String value )
    {
    this.interview = value;
    }

  public java.lang.String getExmatriculated()
    {
    return exmatriculated;
    }

  public void setExmatriculated( java.lang.String value )
    {
    this.exmatriculated = value;
    }

  public java.lang.String getSeconddegree()
    {
    return seconddegree;
    }

  public void setSeconddegree( java.lang.String value )
    {
    this.seconddegree = value;
    }

  public java.lang.String getDatepregraduation()
    {
    return datepregraduation;
    }

  public void setDatepregraduation( java.lang.String value )
    {
    this.datepregraduation = value;
    }

  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.document[] getDocuments()
    {
    return documents;
    }

  public void setDocuments( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.savestudinfos_wsd_hk2.document[] value )
    {
    this.documents = value;
    }
  }
