// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:51:26 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk1;

public class document implements java.io.Serializable
  {
  private java.lang.String title;
  private java.lang.String type;
  private java.lang.String existing;

  public java.lang.String getTitle()
    {
    return title;
    }

  public void setTitle( java.lang.String value )
    {
    this.title = value;
    }

  public java.lang.String getType()
    {
    return type;
    }

  public void setType( java.lang.String value )
    {
    this.type = value;
    }

  public java.lang.String getExisting()
    {
    return existing;
    }

  public void setExisting( java.lang.String value )
    {
    this.existing = value;
    }
  }
