// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:51:26 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk1;

import electric.util.async.Async;

public interface IsetApplicantInfos_WSD_HK1_PortType
  {
  public void setApplicantInfos( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk1.setApplicantInfos setApplicantInfos , Async result );
  }
