// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 22 20:34:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1;

public class exam implements java.io.Serializable
  {
  private java.lang.String _EXAMID;
  private java.lang.String examtype;

  public java.lang.String get_EXAMID()
    {
    return _EXAMID;
    }

  public void set_EXAMID( java.lang.String value )
    {
    this._EXAMID = value;
    }

  public java.lang.String getExamtype()
    {
    return examtype;
    }

  public void setExamtype( java.lang.String value )
    {
    this.examtype = value;
    }
  }
