// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 22 20:34:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class getExamFromCourse_WSD_HK1Helper
  {
  public static IgetExamFromCourse_WSD_HK1_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/Desktop/ccrepository/unterordner/workspace82/Support/src/com/webmethods/caf/is/wsclient/campusconnect/utils/exams/getexamfromcourse_wsd_hk1/getExamFromCourse_WSD_HK1.wsdl" );
    }

  public static IgetExamFromCourse_WSD_HK1_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IgetExamFromCourse_WSD_HK1_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IgetExamFromCourse_WSD_HK1_PortType) Registry.bind( url, IgetExamFromCourse_WSD_HK1_PortType.class, context );
    }
  }
