// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 22 20:34:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1;

public class getExamFromCourseResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1.exam[] outExams;
  private java.lang.String outExamId;

  public com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1.exam[] getOutExams()
    {
    return outExams;
    }

  public void setOutExams( com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1.exam[] value )
    {
    this.outExams = value;
    }

  public java.lang.String getOutExamId()
    {
    return outExamId;
    }

  public void setOutExamId( java.lang.String value )
    {
    this.outExamId = value;
    }
  }
