// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 22 20:34:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1;

public class getExamFromCourse implements java.io.Serializable
  {
  private java.lang.String courseId;

  public java.lang.String getCourseId()
    {
    return courseId;
    }

  public void setCourseId( java.lang.String value )
    {
    this.courseId = value;
    }
  }
