// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 22 20:34:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1;

public interface IgetExamFromCourse_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1.getExamFromCourseResponse getExamFromCourse( com.webmethods.caf.is.wsclient.campusconnect.utils.exams.getexamfromcourse_wsd_hk1.getExamFromCourse getExamFromCourse );
  }
