// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Jan 11 15:21:05 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_3;

public interface IloadFilteredCourses_WSD_3_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_3.loadFilteredCoursesOutput loadFilteredCourses( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_3.loadFilteredCoursesInput loadFilteredCoursesInput );
  }
