// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 20:56:50 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1;

public class exam implements java.io.Serializable
  {
  private java.lang.String _COURSEID;
  private java.lang.String _PROFESSORID;
  private java.lang.String _EXAMDATE;
  private java.lang.String _EXAMTIME;
  private java.lang.String _EXAMROOM;
  private java.lang.String _AMOUNTREGISTERED;
  private java.lang.String _EQUIVALENTID;

  public java.lang.String get_COURSEID()
    {
    return _COURSEID;
    }

  public void set_COURSEID( java.lang.String value )
    {
    this._COURSEID = value;
    }

  public java.lang.String get_PROFESSORID()
    {
    return _PROFESSORID;
    }

  public void set_PROFESSORID( java.lang.String value )
    {
    this._PROFESSORID = value;
    }

  public java.lang.String get_EXAMDATE()
    {
    return _EXAMDATE;
    }

  public void set_EXAMDATE( java.lang.String value )
    {
    this._EXAMDATE = value;
    }

  public java.lang.String get_EXAMTIME()
    {
    return _EXAMTIME;
    }

  public void set_EXAMTIME( java.lang.String value )
    {
    this._EXAMTIME = value;
    }

  public java.lang.String get_EXAMROOM()
    {
    return _EXAMROOM;
    }

  public void set_EXAMROOM( java.lang.String value )
    {
    this._EXAMROOM = value;
    }

  public java.lang.String get_AMOUNTREGISTERED()
    {
    return _AMOUNTREGISTERED;
    }

  public void set_AMOUNTREGISTERED( java.lang.String value )
    {
    this._AMOUNTREGISTERED = value;
    }

  public java.lang.String get_EQUIVALENTID()
    {
    return _EQUIVALENTID;
    }

  public void set_EQUIVALENTID( java.lang.String value )
    {
    this._EQUIVALENTID = value;
    }
  }
