// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 20:56:50 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1;

public interface IstudExam_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1.studExamsListResponse studExamsList( com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1.studExamsList studExamsList );
  }
