// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 20:56:50 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1;

public class studExamsList implements java.io.Serializable
  {
  private java.lang.String studId;

  public java.lang.String getStudId()
    {
    return studId;
    }

  public void setStudId( java.lang.String value )
    {
    this.studId = value;
    }
  }
