// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 20:56:50 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1;

public class studExamsListResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1.exam[] outExams;

  public com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1.exam[] getOutExams()
    {
    return outExams;
    }

  public void setOutExams( com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.studexam_wsd_hk1.exam[] value )
    {
    this.outExams = value;
    }
  }
