// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 21:43:29 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.showregisteredstudentsexam_wsd_hk1;

public class showRegisteredStudentsExam implements java.io.Serializable
  {
  private java.lang.String examId;

  public java.lang.String getExamId()
    {
    return examId;
    }

  public void setExamId( java.lang.String value )
    {
    this.examId = value;
    }
  }
