// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:54:29 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.showenrolledstuds_wsd;

public interface IshowEnrolledStuds_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.showenrolledstuds_wsd.studDetails[] showEnrolledStuds( com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.showenrolledstuds_wsd.showEnrolledStuds showEnrolledStuds );
  }
