// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:54:29 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.showenrolledstuds_wsd;

public class showEnrolledStuds implements java.io.Serializable
  {
  }
