// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:31:24 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setstudstate_wsd_hk1;

public interface IsetStudState_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setstudstate_wsd_hk1.setStudStateResponse setStudState( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setstudstate_wsd_hk1.setStudState setStudState );
  }
