// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:31:24 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setstudstate_wsd_hk1;

public class setStudStateResponse implements java.io.Serializable
  {
  private java.lang.String outputMessage;

  public java.lang.String getOutputMessage()
    {
    return outputMessage;
    }

  public void setOutputMessage( java.lang.String value )
    {
    this.outputMessage = value;
    }
  }
