// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:31:24 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setstudstate_wsd_hk1;

public class setStudState implements java.io.Serializable
  {
  private java.math.BigDecimal studId;
  private java.math.BigDecimal activeStatus;

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }

  public java.math.BigDecimal getActiveStatus()
    {
    return activeStatus;
    }

  public void setActiveStatus( java.math.BigDecimal value )
    {
    this.activeStatus = value;
    }
  }
