// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:33:21 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class deregisterExam_WSDHelper
  {
  public static IderegisterExam_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/examderegistration/deregisterexam_wsd/deregisterExam_WSD.wsdl" );
    }

  public static IderegisterExam_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IderegisterExam_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IderegisterExam_WSD_PortType) Registry.bind( url, IderegisterExam_WSD_PortType.class, context );
    }
  }
