// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:33:21 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd;

public class deregisterExam implements java.io.Serializable
  {
  private java.lang.String examId;
  private java.lang.String studId;

  public java.lang.String getExamId()
    {
    return examId;
    }

  public void setExamId( java.lang.String value )
    {
    this.examId = value;
    }

  public java.lang.String getStudId()
    {
    return studId;
    }

  public void setStudId( java.lang.String value )
    {
    this.studId = value;
    }
  }
