// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:33:21 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd;

public interface IderegisterExam_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd.deregisterExamResponse deregisterExam( com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd.deregisterExam deregisterExam );
  }
