// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:53:47 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest;

public interface Iregistercoursestest_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest.registerCoursesOutput registerCourses( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest.registerCoursesInput registerCoursesInput );
  }
