// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:53:47 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class registercoursestestHelper
  {
  public static Iregistercoursestest_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/Desktop/ccrepository/unterordner/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/courseregistration/registercoursestest/registercoursestest.wsdl" );
    }

  public static Iregistercoursestest_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static Iregistercoursestest_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (Iregistercoursestest_PortType) Registry.bind( url, Iregistercoursestest_PortType.class, context );
    }
  }
