// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:53:47 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest;

public class registerCoursesOutput implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest.registeredCourses[] output;
  private java.lang.String hidden;

  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest.registeredCourses[] getOutput()
    {
    return output;
    }

  public void setOutput( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest.registeredCourses[] value )
    {
    this.output = value;
    }

  public java.lang.String getHidden()
    {
    return hidden;
    }

  public void setHidden( java.lang.String value )
    {
    this.hidden = value;
    }
  }
