// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:53:47 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercoursestest;

public class registerCoursesInput implements java.io.Serializable
  {
  private java.lang.String[] inputCourses;
  private java.math.BigDecimal studId;

  public java.lang.String[] getInputCourses()
    {
    return inputCourses;
    }

  public void setInputCourses( java.lang.String[] value )
    {
    this.inputCourses = value;
    }

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }
  }
