// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Mon Dec 30 03:46:44 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd;

public class savePersonalDataStud implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd.studInfo studInfo = new com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd.studInfo();

public com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd.studInfo getStudInfo()
    {
    return studInfo;
    }

  public void setStudInfo( com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd.studInfo value )
    {
    this.studInfo = value;
    }
  }
