// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 12:01:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1;

public class enrollment implements java.io.Serializable
  {
  private java.lang.String citizenship;
  private java.lang.String isenrolled;
  private java.lang.String entrancetest;
  private java.lang.String nc;
  private java.lang.String interview;
  private java.lang.String exmatriculated;
  private java.lang.String seconddegree;
  private java.lang.String datepregraduation;
  private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.document[] documents;
  private java.lang.String completed;
  private java.lang.String payed;
  private java.lang.String scoringresult;

  public java.lang.String getCitizenship()
    {
    return citizenship;
    }

  public void setCitizenship( java.lang.String value )
    {
    this.citizenship = value;
    }

  public java.lang.String getIsenrolled()
    {
    return isenrolled;
    }

  public void setIsenrolled( java.lang.String value )
    {
    this.isenrolled = value;
    }

  public java.lang.String getEntrancetest()
    {
    return entrancetest;
    }

  public void setEntrancetest( java.lang.String value )
    {
    this.entrancetest = value;
    }

  public java.lang.String getNc()
    {
    return nc;
    }

  public void setNc( java.lang.String value )
    {
    this.nc = value;
    }

  public java.lang.String getInterview()
    {
    return interview;
    }

  public void setInterview( java.lang.String value )
    {
    this.interview = value;
    }

  public java.lang.String getExmatriculated()
    {
    return exmatriculated;
    }

  public void setExmatriculated( java.lang.String value )
    {
    this.exmatriculated = value;
    }

  public java.lang.String getSeconddegree()
    {
    return seconddegree;
    }

  public void setSeconddegree( java.lang.String value )
    {
    this.seconddegree = value;
    }

  public java.lang.String getDatepregraduation()
    {
    return datepregraduation;
    }

  public void setDatepregraduation( java.lang.String value )
    {
    this.datepregraduation = value;
    }

  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.document[] getDocuments()
    {
    return documents;
    }

  public void setDocuments( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.document[] value )
    {
    this.documents = value;
    }

  public java.lang.String getCompleted()
    {
    return completed;
    }

  public void setCompleted( java.lang.String value )
    {
    this.completed = value;
    }

  public java.lang.String getPayed()
    {
    return payed;
    }

  public void setPayed( java.lang.String value )
    {
    this.payed = value;
    }

  public java.lang.String getScoringresult()
    {
    return scoringresult;
    }

  public void setScoringresult( java.lang.String value )
    {
    this.scoringresult = value;
    }
  }
