// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 12:01:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1;

public class getApplicantInfos implements java.io.Serializable
  {
  private java.lang.String applicantId;

  public java.lang.String getApplicantId()
    {
    return applicantId;
    }

  public void setApplicantId( java.lang.String value )
    {
    this.applicantId = value;
    }
  }
