// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 12:01:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1;

public interface IgetApplicantInfos_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.getApplicantInfosResponse getApplicantInfos( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.getApplicantInfos getApplicantInfos );
  }
