// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 12:01:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1;

public class student implements java.io.Serializable
  {
  private java.lang.String _FIRSTNAME;
  private java.lang.String _LASTNAME;
  private java.lang.String _ADDRESSLINE1;
  private java.lang.String _ADDRESSLINE2;
  private java.lang.String _DEGREEPROGRAM;
  private java.lang.String _EMAIL;
  private java.lang.String _PHONE;
  private java.lang.String _DOB;
  private java.math.BigDecimal _TERM;
  private java.lang.String _REGISTERED;
  private java.math.BigDecimal _ACTIVE;
private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.enrollment enrollment = new com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.enrollment();
  public java.lang.String get_FIRSTNAME()
    {
    return _FIRSTNAME;
    }

  public void set_FIRSTNAME( java.lang.String value )
    {
    this._FIRSTNAME = value;
    }

  public java.lang.String get_LASTNAME()
    {
    return _LASTNAME;
    }

  public void set_LASTNAME( java.lang.String value )
    {
    this._LASTNAME = value;
    }

  public java.lang.String get_ADDRESSLINE1()
    {
    return _ADDRESSLINE1;
    }

  public void set_ADDRESSLINE1( java.lang.String value )
    {
    this._ADDRESSLINE1 = value;
    }

  public java.lang.String get_ADDRESSLINE2()
    {
    return _ADDRESSLINE2;
    }

  public void set_ADDRESSLINE2( java.lang.String value )
    {
    this._ADDRESSLINE2 = value;
    }

  public java.lang.String get_DEGREEPROGRAM()
    {
    return _DEGREEPROGRAM;
    }

  public void set_DEGREEPROGRAM( java.lang.String value )
    {
    this._DEGREEPROGRAM = value;
    }

  public java.lang.String get_EMAIL()
    {
    return _EMAIL;
    }

  public void set_EMAIL( java.lang.String value )
    {
    this._EMAIL = value;
    }

  public java.lang.String get_PHONE()
    {
    return _PHONE;
    }

  public void set_PHONE( java.lang.String value )
    {
    this._PHONE = value;
    }

  public java.lang.String get_DOB()
    {
    return _DOB;
    }

  public void set_DOB( java.lang.String value )
    {
    this._DOB = value;
    }

  public java.math.BigDecimal get_TERM()
    {
    return _TERM;
    }

  public void set_TERM( java.math.BigDecimal value )
    {
    this._TERM = value;
    }

  public java.lang.String get_REGISTERED()
    {
    return _REGISTERED;
    }

  public void set_REGISTERED( java.lang.String value )
    {
    this._REGISTERED = value;
    }

  public java.math.BigDecimal get_ACTIVE()
    {
    return _ACTIVE;
    }

  public void set_ACTIVE( java.math.BigDecimal value )
    {
    this._ACTIVE = value;
    }

  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.enrollment getEnrollment()
    {
    return enrollment;
    }

  public void setEnrollment( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk1.enrollment value )
    {
    this.enrollment = value;
    }
  }
