// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 18:39:27 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2;

public class hiddenDoc implements java.io.Serializable
  {
  private java.lang.String hidden;

  public java.lang.String getHidden()
    {
    return hidden;
    }

  public void setHidden( java.lang.String value )
    {
    this.hidden = value;
    }
  }
