// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 18:39:26 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2;

public interface IregisterCourses_WSD_HK2_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.registerCoursesOutput registerCourses( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.registerCoursesInput registerCoursesInput );
  }
