// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 18:39:27 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2;

public class registerCoursesOutput implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.registeredCourses[] output;
  private java.lang.String hidden;
private com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.hiddenDoc hiddenDoc = new com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.hiddenDoc();

  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.registeredCourses[] getOutput()
    {
    return output;
    }

  public void setOutput( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.registeredCourses[] value )
    {
    this.output = value;
    }

  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.hiddenDoc getHiddenDoc()
    {
    return hiddenDoc;
    }

  public void setHiddenDoc( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2.hiddenDoc value )
    {
    this.hiddenDoc = value;
    }

  public java.lang.String getHidden()
    {
    return hidden;
    }

  public void setHidden( java.lang.String value )
    {
    this.hidden = value;
    }
  }
