// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 18:39:26 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd_hk2;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class registerCourses_WSD_HK2Helper
  {
  public static IregisterCourses_WSD_HK2_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/Desktop/ccrepository/unterordner/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/courseregistration/registercourses_wsd_hk2/registerCourses_WSD_HK2.wsdl" );
    }

  public static IregisterCourses_WSD_HK2_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IregisterCourses_WSD_HK2_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IregisterCourses_WSD_HK2_PortType) Registry.bind( url, IregisterCourses_WSD_HK2_PortType.class, context );
    }
  }
