// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 21:51:16 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getsinglegrade_wsd_hk1;

public class getSingleGradeResponse implements java.io.Serializable
  {
  private java.lang.String grade;

  public java.lang.String getGrade()
    {
    return grade;
    }

  public void setGrade( java.lang.String value )
    {
    this.grade = value;
    }
  }
