// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 21:51:16 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getsinglegrade_wsd_hk1;

public class getSingleGrade implements java.io.Serializable
  {
  private java.math.BigDecimal studId;
  private java.math.BigDecimal courseId;

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }

  public java.math.BigDecimal getCourseId()
    {
    return courseId;
    }

  public void setCourseId( java.math.BigDecimal value )
    {
    this.courseId = value;
    }
  }
