// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 21:51:16 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getsinglegrade_wsd_hk1;

public interface IgetSingleGrade_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getsinglegrade_wsd_hk1.getSingleGradeResponse getSingleGrade( com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getsinglegrade_wsd_hk1.getSingleGrade getSingleGrade );
  }
