// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 16:03:18 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd_hk1;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class deregisterExam_WSD_HK1Helper
  {
  public static IderegisterExam_WSD_HK1_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/Support/src/com/webmethods/caf/is/wsclient/campusconnect/work/examderegistration/deregisterexam_wsd_hk1/deregisterExam_WSD_HK1.wsdl" );
    }

  public static IderegisterExam_WSD_HK1_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IderegisterExam_WSD_HK1_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IderegisterExam_WSD_HK1_PortType) Registry.bind( url, IderegisterExam_WSD_HK1_PortType.class, context );
    }
  }
