// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 16:03:18 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd_hk1;

public interface IderegisterExam_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd_hk1.deregisterExamResponse deregisterExam( com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd_hk1.deregisterExam deregisterExam );
  }
