// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 22:01:06 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd;

public class searchCourse implements java.io.Serializable
  {
  private java.lang.String searchString;

  public java.lang.String getSearchString()
    {
    return searchString;
    }

  public void setSearchString( java.lang.String value )
    {
    this.searchString = value;
    }
  }
