// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Jan 11 15:37:26 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd;

public interface IshowPersonalDataStud_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd.showPersonalDataStudResponse showPersonalDataStud( com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd.showPersonalDataStud showPersonalDataStud );
  }
