// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:28:32 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd;

public interface IregisterExam_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd.registerExamResponse registerExam( com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd.registerExam registerExam );
  }
