// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:28:32 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd;

public class registerExam implements java.io.Serializable
  {
  private java.lang.String courseId;
  private java.lang.String studId;

  public java.lang.String getCourseId()
    {
    return courseId;
    }

  public void setCourseId( java.lang.String value )
    {
    this.courseId = value;
    }

  public java.lang.String getStudId()
    {
    return studId;
    }

  public void setStudId( java.lang.String value )
    {
    this.studId = value;
    }
  }
