// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:28:32 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class registerExam_WSDHelper
  {
  public static IregisterExam_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/examregistration/registerexam_wsd/registerExam_WSD.wsdl" );
    }

  public static IregisterExam_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IregisterExam_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IregisterExam_WSD_PortType) Registry.bind( url, IregisterExam_WSD_PortType.class, context );
    }
  }
