// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Dec 24 01:38:27 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd;

public class loadFilteredCoursesInput implements java.io.Serializable
  {
  private java.math.BigDecimal studId;

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }
  }
