// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 16:13:15 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd;

public interface IderegisterExam_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd.deregisterExamResponse deregisterExam( com.webmethods.caf.is.wsclient.campusconnect.work.examderegistration.deregisterexam_wsd.deregisterExam deregisterExam );
  }
