// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 19:29:46 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1;

public interface IgetCourseDetails_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1.getCourseDetailsResponse getCourseDetails( com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1.getCourseDetails getCourseDetails );
  }
