// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 29 18:54:48 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.courses.listcoursessingleprof_wsd_hk1;

public interface IlistCoursesSingleProf_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.utils.courses.listcoursessingleprof_wsd_hk1.listCoursesSingleProfResponse listCoursesSingleProf( com.webmethods.caf.is.wsclient.campusconnect.utils.courses.listcoursessingleprof_wsd_hk1.listCoursesSingleProf listCoursesSingleProf );
  }
