// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 29 18:54:48 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.courses.listcoursessingleprof_wsd_hk1;

public class listCoursesSingleProfResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.utils.courses.listcoursessingleprof_wsd_hk1.course[] courses;

  public com.webmethods.caf.is.wsclient.campusconnect.utils.courses.listcoursessingleprof_wsd_hk1.course[] getCourses()
    {
    return courses;
    }

  public void setCourses( com.webmethods.caf.is.wsclient.campusconnect.utils.courses.listcoursessingleprof_wsd_hk1.course[] value )
    {
    this.courses = value;
    }
  }
