// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 29 18:54:48 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.courses.listcoursessingleprof_wsd_hk1;

public class listCoursesSingleProf implements java.io.Serializable
  {
  private java.lang.String ProfId;

  public java.lang.String getProfId()
    {
    return ProfId;
    }

  public void setProfId( java.lang.String value )
    {
    this.ProfId = value;
    }
  }
