// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 12:00:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1;

public class getIdCardResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1.idCard idCard = new com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1.idCard();

public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1.idCard getIdCard()
    {
    return idCard;
    }

  public void setIdCard( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1.idCard value )
    {
    this.idCard = value;
    }
  }
