// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 12:00:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1;

public class getIdCard implements java.io.Serializable
  {
  private java.lang.String _STUDENTID;

  public java.lang.String get_STUDENTID()
    {
    return _STUDENTID;
    }

  public void set_STUDENTID( java.lang.String value )
    {
    this._STUDENTID = value;
    }
  }
