// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 12:00:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1;

public class idCard implements java.io.Serializable
  {
  private java.lang.String _FIRSTNAME;
  private java.lang.String _LASTNAME;
  private java.lang.String _ADDRESSLINE1;
  private java.lang.String _ADDRESSLINE2;
  private java.lang.String _DEGREEPROGRAM;
  private java.lang.String _EMAIL;
  private java.lang.String _DOB;
  private java.math.BigDecimal _TERM;
  private java.lang.String _STUDENTID;
  private java.lang.String currentbegin;
  private java.lang.String currentend;

  public java.lang.String get_FIRSTNAME()
    {
    return _FIRSTNAME;
    }

  public void set_FIRSTNAME( java.lang.String value )
    {
    this._FIRSTNAME = value;
    }

  public java.lang.String get_LASTNAME()
    {
    return _LASTNAME;
    }

  public void set_LASTNAME( java.lang.String value )
    {
    this._LASTNAME = value;
    }

  public java.lang.String get_ADDRESSLINE1()
    {
    return _ADDRESSLINE1;
    }

  public void set_ADDRESSLINE1( java.lang.String value )
    {
    this._ADDRESSLINE1 = value;
    }

  public java.lang.String get_ADDRESSLINE2()
    {
    return _ADDRESSLINE2;
    }

  public void set_ADDRESSLINE2( java.lang.String value )
    {
    this._ADDRESSLINE2 = value;
    }

  public java.lang.String get_DEGREEPROGRAM()
    {
    return _DEGREEPROGRAM;
    }

  public void set_DEGREEPROGRAM( java.lang.String value )
    {
    this._DEGREEPROGRAM = value;
    }

  public java.lang.String get_EMAIL()
    {
    return _EMAIL;
    }

  public void set_EMAIL( java.lang.String value )
    {
    this._EMAIL = value;
    }

  public java.lang.String get_DOB()
    {
    return _DOB;
    }

  public void set_DOB( java.lang.String value )
    {
    this._DOB = value;
    }

  public java.math.BigDecimal get_TERM()
    {
    return _TERM;
    }

  public void set_TERM( java.math.BigDecimal value )
    {
    this._TERM = value;
    }

  public java.lang.String get_STUDENTID()
    {
    return _STUDENTID;
    }

  public void set_STUDENTID( java.lang.String value )
    {
    this._STUDENTID = value;
    }

  public java.lang.String getCurrentbegin()
    {
    return currentbegin;
    }

  public void setCurrentbegin( java.lang.String value )
    {
    this.currentbegin = value;
    }

  public java.lang.String getCurrentend()
    {
    return currentend;
    }

  public void setCurrentend( java.lang.String value )
    {
    this.currentend = value;
    }
  }
