// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 12:00:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1;

public interface IgetIdCard_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1.getIdCardResponse getIdCard( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getidcard_wsd_hk1.getIdCard getIdCard );
  }
