/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/


public class ExamregTsuss extends com.softwareag.entirex.aci.Tester2 {

	protected void setFields() {
		addField("2  #STUDENTID (P17/V)",false,true,4,"suss_output.[V]._studentid");
		addField("2  #FIRSTNAME (A10/V)",false,true,4,"suss_output.[V]._firstname");
		addField("2  #LASTNAME (A32/V)",false,true,4,"suss_output.[V]._lastname");
		addField("2  #REGISTERED (A10/V)",false,true,4,"suss_output.[V]._registered");
		addField("2  #TERM (P3/V)",false,true,4,"suss_output.[V]._term");
		addField("2  #ACTIVE (P1/V)",false,true,4,"suss_output.[V]._active");
		addField("2  #DEGREEPROGRAM (A10/V)",false,true,4,"suss_output.[V]._degreeprogram");
		addField("2  #DOB (A10/V)",false,true,4,"suss_output.[V]._dob");
		addField("2  #ADDRESSLINE1 (A32/V)",false,true,4,"suss_output.[V]._addressline1");
		addField("2  #ADDRESSLINE2 (A32/V)",false,true,4,"suss_output.[V]._addressline2");
		addField("2  #PHONE (A32/V)",false,true,4,"suss_output.[V]._phone");
		addField("2  #EMAIL (A32/V)",false,true,4,"suss_output.[V]._email");
	}

	public static void main(String[] args) {
		new ExamregTsuss().test(args, Examreg.class, "suss");
	}
}
