// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 20:52:16 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_bugtest1;

public interface IloadStudRegisteredCourses_WSD_Bugtest1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_bugtest1.loadStudRegisteredCoursesResponse loadStudRegisteredCourses( com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_bugtest1.loadStudRegisteredCourses loadStudRegisteredCourses );
  }
