// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 20:52:16 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_bugtest1;

public class loadStudRegisteredCoursesResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_bugtest1.course[] outCourses;

  public com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_bugtest1.course[] getOutCourses()
    {
    return outCourses;
    }

  public void setOutCourses( com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_bugtest1.course[] value )
    {
    this.outCourses = value;
    }
  }
