// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 20:52:16 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd_bugtest1;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class loadStudRegisteredCourses_WSD_Bugtest1Helper
  {
  public static IloadStudRegisteredCourses_WSD_Bugtest1_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/Support/src/com/webmethods/caf/is/wsclient/campusconnect/work/coursederegistration/loadstudregisteredcourses_wsd_bugtest1/loadStudRegisteredCourses_WSD_Bugtest1.wsdl" );
    }

  public static IloadStudRegisteredCourses_WSD_Bugtest1_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IloadStudRegisteredCourses_WSD_Bugtest1_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IloadStudRegisteredCourses_WSD_Bugtest1_PortType) Registry.bind( url, IloadStudRegisteredCourses_WSD_Bugtest1_PortType.class, context );
    }
  }
