// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Mon Dec 30 03:46:44 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd;

public interface IsavePersonalDataStudwsd_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd.savePersonalDataStudResponse savePersonalDataStud( com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd.savePersonalDataStud savePersonalDataStud );
  }
