// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Mon Dec 30 03:46:44 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd;

public class savePersonalDataStudResponse implements java.io.Serializable
  {
  private java.lang.String outputMessage;

  public java.lang.String getOutputMessage()
    {
    return outputMessage;
    }

  public void setOutputMessage( java.lang.String value )
    {
    this.outputMessage = value;
    }
  }
