// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Mon Dec 30 03:46:44 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.savepersonaldatastudwsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class savePersonalDataStudwsdHelper
  {
  public static IsavePersonalDataStudwsd_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/editpersonaldatastud/savepersonaldatastudwsd/savePersonalDataStudwsd.wsdl" );
    }

  public static IsavePersonalDataStudwsd_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IsavePersonalDataStudwsd_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IsavePersonalDataStudwsd_PortType) Registry.bind( url, IsavePersonalDataStudwsd_PortType.class, context );
    }
  }
