/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/


public class ExamregTsci extends com.softwareag.entirex.aci.Tester2 {

	protected void setFields() {
		addField("1  #COURSEID (P9)",true,false,1,"1");
		addField("1  #DEGREEPROGRAM (A32)",false,true,4,"sci_degreeprogram");
		addField("1  #EQUIVALENTID (P2)",false,true,4,"sci_equivalentid");
		addField("1  #PROFESSORID (P9)",false,true,4,"sci_professorid");
		addField("1  #COURSENAME (A32)",false,true,4,"sci_coursename");
		addField("1  #TERM (A32)",false,true,4,"sci_term");
		addField("1  #MAXPARTICIPANTS (P9)",false,true,4,"sci_maxparticipants");
		addField("1  #COURSEDAY (A32)",false,true,4,"sci_courseday");
		addField("1  #COURSETIME (A32)",false,true,4,"sci_coursetime");
		addField("1  #COURSEROOM (A32)",false,true,4,"sci_courseroom");
		addField("1  #COURSEFINISH (P1)",false,true,4,"sci_coursefinish");
		addField("1  #AMOUNTREGISTERED (P9)",false,true,4,"sci_amountregistered");
		addField("1  #MESSAGE (A40)",false,true,4,"sci_message");
	}

	public static void main(String[] args) {
		new ExamregTsci().test(args, Examreg.class, "sci");
	}
}
