/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/


public class ExamregTsupi extends com.softwareag.entirex.aci.Tester2 {

	protected void setFields() {
		addField("1  #PROFID (P9)",true,false,1,"1");
		addField("1  #PFIRSTNAME (A32)",false,true,4,"supi_pfirstname");
		addField("1  #PLASTNAME (A32)",false,true,4,"supi_plastname");
		addField("1  #PTITEL (A32)",false,true,4,"supi_ptitel");
		addField("1  #PCHAIR (A32)",false,true,4,"supi_pchair");
		addField("1  #MESSAGE (A40)",false,true,4,"supi_message");
	}

	public static void main(String[] args) {
		new ExamregTsupi().test(args, Examreg.class, "supi");
	}
}
