// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 11:36:10 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.administration.editstudent2_wsd_hk1;

public class editStudent2 implements java.io.Serializable
  {
  private java.math.BigDecimal _STUDENTID;
  private java.lang.String _ADDRESSLINE1;
  private java.lang.String _ADDRESSLINE2;
  private java.lang.String _EMAIL;
  private java.lang.String _PHONE;

  public java.math.BigDecimal get_STUDENTID()
    {
    return _STUDENTID;
    }

  public void set_STUDENTID( java.math.BigDecimal value )
    {
    this._STUDENTID = value;
    }

  public java.lang.String get_ADDRESSLINE1()
    {
    return _ADDRESSLINE1;
    }

  public void set_ADDRESSLINE1( java.lang.String value )
    {
    this._ADDRESSLINE1 = value;
    }

  public java.lang.String get_ADDRESSLINE2()
    {
    return _ADDRESSLINE2;
    }

  public void set_ADDRESSLINE2( java.lang.String value )
    {
    this._ADDRESSLINE2 = value;
    }

  public java.lang.String get_EMAIL()
    {
    return _EMAIL;
    }

  public void set_EMAIL( java.lang.String value )
    {
    this._EMAIL = value;
    }

  public java.lang.String get_PHONE()
    {
    return _PHONE;
    }

  public void set_PHONE( java.lang.String value )
    {
    this._PHONE = value;
    }
  }
