// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 11:36:09 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.administration.editstudent2_wsd_hk1;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class editStudent2_WSD_HK1Helper
  {
  public static IeditStudent2_WSD_HK1_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/Desktop/ccrepository/unterordner/workspace82/TestPortletProject/src/com/webmethods/caf/is/wsclient/campusconnect/work/administration/editstudent2_wsd_hk1/editStudent2_WSD_HK1.wsdl" );
    }

  public static IeditStudent2_WSD_HK1_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IeditStudent2_WSD_HK1_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IeditStudent2_WSD_HK1_PortType) Registry.bind( url, IeditStudent2_WSD_HK1_PortType.class, context );
    }
  }
