// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 11:36:08 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.administration.editstudent2_wsd_hk1;

public interface IeditStudent2_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.administration.editstudent2_wsd_hk1.editStudent2Response editStudent2( com.webmethods.caf.is.wsclient.campusconnect.work.administration.editstudent2_wsd_hk1.editStudent2 editStudent2 );
  }
