// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 29 14:14:27 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class CampusConnect_utils_coursesServiceHelper
  {
  public static ICampusConnect_utils_coursesPortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/Desktop/ccrepository/unterordner/workspace82/CampusConnect_HK/src/com/webmethods/caf/is/wsclient/campusconnect/utils/courses/getcoursedetails/getCourseDetails.wsdl" );
    }

  public static ICampusConnect_utils_coursesPortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static ICampusConnect_utils_coursesPortType bind( String url , Context context )
    throws RegistryException
    {
    return (ICampusConnect_utils_coursesPortType) Registry.bind( url, ICampusConnect_utils_coursesPortType.class, context );
    }
  }
