// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 29 14:14:27 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails;

public interface ICampusConnect_utils_coursesPortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails.__course getCourseDetails( java.lang.String id );
  }
