// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 22 20:00:19 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.administration.editstudent2_wsd_hk1;

public class editStudent2Response implements java.io.Serializable
  {
  private java.lang.String message;

  public java.lang.String getMessage()
    {
    return message;
    }

  public void setMessage( java.lang.String value )
    {
    this.message = value;
    }
  }
