/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/


public class ExamregTsti extends com.softwareag.entirex.aci.Tester2 {

	protected void setFields() {
		addField("1  #STUDENTID (P9)",true,false,1,"1");
		addField("1  #FIRSTNAME (A32)",false,true,4,"sti_firstname");
		addField("1  #LASTNAME (A32)",false,true,4,"sti_lastname");
		addField("1  #TERM (P3)",false,true,4,"sti_term");
		addField("1  #DOB (A10)",false,true,4,"sti_dob");
		addField("1  #DEGREEPROGRAM (A32)",false,true,4,"sti_degreeprogram");
		addField("1  #COURSENAMES (A32/10)",false,true,4,"sti_coursenames.[10]");
		addField("1  #COURSEIDS (P9/10)",false,true,4,"sti_courseids.[10]");
		addField("1  #GRADES (N1.1/10)",false,true,4,"sti_grades.[10]");
		addField("1  #FINALGRADE (P1.1)",false,true,4,"sti_finalgrade");
		addField("1  #MESSAGE (A40)",false,true,4,"sti_message");
	}

	public static void main(String[] args) {
		new ExamregTsti().test(args, Examreg.class, "sti");
	}
}
