// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 20:15:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.deregistercourses_wsd;

public class deregisterCourses implements java.io.Serializable
  {
  private java.lang.String studId;
  private java.lang.String[] courseIds;

  public java.lang.String getStudId()
    {
    return studId;
    }

  public void setStudId( java.lang.String value )
    {
    this.studId = value;
    }

  public java.lang.String[] getCourseIds()
    {
    return courseIds;
    }

  public void setCourseIds( java.lang.String[] value )
    {
    this.courseIds = value;
    }
  }
