// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 20:15:30 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.deregistercourses_wsd;

public interface IderegisterCourses_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.deregistercourses_wsd.deregisterCoursesResponse deregisterCourses( com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.deregistercourses_wsd.deregisterCourses deregisterCourses );
  }
