// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 20:45:19 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.deregistercourses_wsd;

public interface IderegisterCourses_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.deregistercourses_wsd.deletedCourses[] deregisterCourses( com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.deregistercourses_wsd.deregisterCourses deregisterCourses );
  }
