// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Dec 26 05:26:45 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd;

public interface IshowPersonalData_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd.showPersonalDataResponse showPersonalData( com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd.showPersonalData showPersonalData );
  }
