// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Dec 26 05:26:45 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd;

public class showPersonalData implements java.io.Serializable
  {
  private java.lang.String studentId;

  public java.lang.String getStudentId()
    {
    return studentId;
    }

  public void setStudentId( java.lang.String value )
    {
    this.studentId = value;
    }
  }
