// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Dec 26 05:26:45 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd;

public class showPersonalDataResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd.student student = new com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd.student();

public com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd.student getStudent()
    {
    return student;
    }

  public void setStudent( com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd.student value )
    {
    this.student = value;
    }
  }
