// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 05:17:49 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1;

public class eatingplan_local implements java.io.Serializable
  {
  private java.util.Date date;
  private java.lang.String meal;

  public java.util.Date getDate()
    {
    return date;
    }

  public void setDate( java.util.Date value )
    {
    this.date = value;
    }

  public java.lang.String getMeal()
    {
    return meal;
    }

  public void setMeal( java.lang.String value )
    {
    this.meal = value;
    }
  }
