// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 05:17:48 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1;

public interface IshowEating_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.showEatingResponse showEating( com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.showEating showEating );
  }
