// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 05:17:49 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1;

public class showEating implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.eatingplan_local[] eatingplan_local;
  private java.util.Date date_current;
private com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.eatingplan eatingplan = new com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.eatingplan();

  public com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.eatingplan getEatingplan()
    {
    return eatingplan;
    }

  public void setEatingplan( com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.eatingplan value )
    {
    this.eatingplan = value;
    }

  public com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.eatingplan_local[] getEatingplan_local()
    {
    return eatingplan_local;
    }

  public void setEatingplan_local( com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1.eatingplan_local[] value )
    {
    this.eatingplan_local = value;
    }

  public java.util.Date getDate_current()
    {
    return date_current;
    }

  public void setDate_current( java.util.Date value )
    {
    this.date_current = value;
    }
  }
