// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 05:17:48 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.eating.showeating_wsd_hk1;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class showEating_WSD_HK1Helper
  {
  public static IshowEating_WSD_HK1_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/Support/src/com/webmethods/caf/is/wsclient/campusconnect/work/eating/showeating_wsd_hk1/showEating_WSD_HK1.wsdl" );
    }

  public static IshowEating_WSD_HK1_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IshowEating_WSD_HK1_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IshowEating_WSD_HK1_PortType) Registry.bind( url, IshowEating_WSD_HK1_PortType.class, context );
    }
  }
