// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 31 13:10:41 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.submitgrade_wsd_hk3;

public interface IsubmitGrade_WSD_HK3_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.submitgrade_wsd_hk3.submitGradeResponse submitGrade( com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.submitgrade_wsd_hk3.submitGrade submitGrade );
  }
