// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 31 13:10:41 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.submitgrade_wsd_hk3;

public class submitGradeResponse implements java.io.Serializable
  {
  private java.lang.String message;

  public java.lang.String getMessage()
    {
    return message;
    }

  public void setMessage( java.lang.String value )
    {
    this.message = value;
    }
  }
