// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:43:44 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.savestudinfos_wsd;

public interface IsaveStudInfos_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.savestudinfos_wsd.saveStudInfosResponse saveStudInfos( com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.savestudinfos_wsd.saveStudInfos saveStudInfos );
  }
