// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 16:06:14 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd;

public interface IregisterExam_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd.registerExamResponse registerExam( com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd.registerExam registerExam );
  }
