// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 16:06:14 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.examregistration.registerexam_wsd;

public class registerExamResponse implements java.io.Serializable
  {
  private java.lang.String outputMessage;
  private java.lang.String test;

  public java.lang.String getOutputMessage()
    {
    return outputMessage;
    }

  public void setOutputMessage( java.lang.String value )
    {
    this.outputMessage = value;
    }

  public java.lang.String getTest()
    {
    return test;
    }

  public void setTest( java.lang.String value )
    {
    this.test = value;
    }
  }
