// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 29 14:10:16 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.showregisteredstudentsexam_wsd_hk1;

public interface IshowRegisteredStudentsExam_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.showregisteredstudentsexam_wsd_hk1.showRegisteredStudentsExamResponse showRegisteredStudentsExam( com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.showregisteredstudentsexam_wsd_hk1.showRegisteredStudentsExam showRegisteredStudentsExam );
  }
