// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 29 14:10:16 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.showregisteredstudentsexam_wsd_hk1;

public class student implements java.io.Serializable
  {
  private java.lang.String _STUDENTID;
  private java.lang.String _FIRSTNAME;
  private java.lang.String _LASTNAME;
  private java.lang.String _REGISTEREDDATE;

  public java.lang.String get_STUDENTID()
    {
    return _STUDENTID;
    }

  public void set_STUDENTID( java.lang.String value )
    {
    this._STUDENTID = value;
    }

  public java.lang.String get_FIRSTNAME()
    {
    return _FIRSTNAME;
    }

  public void set_FIRSTNAME( java.lang.String value )
    {
    this._FIRSTNAME = value;
    }

  public java.lang.String get_LASTNAME()
    {
    return _LASTNAME;
    }

  public void set_LASTNAME( java.lang.String value )
    {
    this._LASTNAME = value;
    }

  public java.lang.String get_REGISTEREDDATE()
    {
    return _REGISTEREDDATE;
    }

  public void set_REGISTEREDDATE( java.lang.String value )
    {
    this._REGISTEREDDATE = value;
    }
  }
