// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 12:31:15 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1;

public class getAllGradesResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1.outGrade[] outGrades;

  public com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1.outGrade[] getOutGrades()
    {
    return outGrades;
    }

  public void setOutGrades( com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1.outGrade[] value )
    {
    this.outGrades = value;
    }
  }
