// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 12:31:15 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1;

public class getAllGrades implements java.io.Serializable
  {
  private java.math.BigDecimal studId;

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }
  }
