// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 21:50:27 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1;

public interface IgetAllGrades_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1.outputGrades[] getAllGrades( com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1.getAllGrades getAllGrades );
  }
