// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 12:31:15 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1;

public class outGrade implements java.io.Serializable
  {
  private java.lang.String courseName;
  private java.lang.String courseId;
  private java.lang.String grade;
  private java.lang.String examtype;
  private java.lang.String _EXAMDATE;
  private java.lang.String _PLASTNAME;
  private java.lang.String _PFIRSTNAME;
  private java.lang.String _PTITEL;
  private java.lang.String _try;

  public java.lang.String getCourseName()
    {
    return courseName;
    }

  public void setCourseName( java.lang.String value )
    {
    this.courseName = value;
    }

  public java.lang.String getCourseId()
    {
    return courseId;
    }

  public void setCourseId( java.lang.String value )
    {
    this.courseId = value;
    }

  public java.lang.String getGrade()
    {
    return grade;
    }

  public void setGrade( java.lang.String value )
    {
    this.grade = value;
    }

  public java.lang.String getExamtype()
    {
    return examtype;
    }

  public void setExamtype( java.lang.String value )
    {
    this.examtype = value;
    }

  public java.lang.String get_EXAMDATE()
    {
    return _EXAMDATE;
    }

  public void set_EXAMDATE( java.lang.String value )
    {
    this._EXAMDATE = value;
    }

  public java.lang.String get_PLASTNAME()
    {
    return _PLASTNAME;
    }

  public void set_PLASTNAME( java.lang.String value )
    {
    this._PLASTNAME = value;
    }

  public java.lang.String get_PFIRSTNAME()
    {
    return _PFIRSTNAME;
    }

  public void set_PFIRSTNAME( java.lang.String value )
    {
    this._PFIRSTNAME = value;
    }

  public java.lang.String get_PTITEL()
    {
    return _PTITEL;
    }

  public void set_PTITEL( java.lang.String value )
    {
    this._PTITEL = value;
    }

  public java.lang.String get_try()
    {
    return _try;
    }

  public void set_try( java.lang.String value )
    {
    this._try = value;
    }
  }
