// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 21:50:27 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.studentgrades.getallgrades_wsd_hk1;

public class outputGrades implements java.io.Serializable
  {
  private java.lang.String courseName;
  private java.lang.String courseId;
  private java.lang.String grade;

  public java.lang.String getCourseName()
    {
    return courseName;
    }

  public void setCourseName( java.lang.String value )
    {
    this.courseName = value;
    }

  public java.lang.String getCourseId()
    {
    return courseId;
    }

  public void setCourseId( java.lang.String value )
    {
    this.courseId = value;
    }

  public java.lang.String getGrade()
    {
    return grade;
    }

  public void setGrade( java.lang.String value )
    {
    this.grade = value;
    }
  }
