// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 22:01:06 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd;

public interface IsearchCourse_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd.courses[] searchCourse( com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd.searchCourse searchCourse );
  }
