// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 22:01:06 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.searchcourse_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class searchCourse_WSDHelper
  {
  public static IsearchCourse_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/searchcourse/searchcourse_wsd/searchCourse_WSD.wsdl" );
    }

  public static IsearchCourse_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IsearchCourse_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IsearchCourse_WSD_PortType) Registry.bind( url, IsearchCourse_WSD_PortType.class, context );
    }
  }
