// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 20:46:22 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd;

public interface IloadStudRegisteredCourses_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd.shortCourseInfo[] loadStudRegisteredCourses( com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd.loadStudRegisteredCourses loadStudRegisteredCourses );
  }
