// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 20:46:22 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class loadStudRegisteredCourses_WSDHelper
  {
  public static IloadStudRegisteredCourses_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/coursederegistration/loadstudregisteredcourses_wsd/loadStudRegisteredCourses_WSD.wsdl" );
    }

  public static IloadStudRegisteredCourses_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IloadStudRegisteredCourses_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IloadStudRegisteredCourses_WSD_PortType) Registry.bind( url, IloadStudRegisteredCourses_WSD_PortType.class, context );
    }
  }
