// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Feb 01 16:10:42 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk1;

public class setApplicantInfos implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk1.student student = new com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk1.student();

public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk1.student getStudent()
    {
    return student;
    }

  public void setStudent( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk1.student value )
    {
    this.student = value;
    }
  }
