// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 31 12:22:24 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.administration.getexmareasons_wsd_mw1;

public class getExmaReasonsResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.administration.getexmareasons_wsd_mw1.reason[] reasons;

  public com.webmethods.caf.is.wsclient.campusconnect.work.administration.getexmareasons_wsd_mw1.reason[] getReasons()
    {
    return reasons;
    }

  public void setReasons( com.webmethods.caf.is.wsclient.campusconnect.work.administration.getexmareasons_wsd_mw1.reason[] value )
    {
    this.reasons = value;
    }
  }
