// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 31 12:22:24 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.administration.getexmareasons_wsd_mw1;

public interface IgetExmaReasons_WSD_MW1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.administration.getexmareasons_wsd_mw1.getExmaReasonsResponse getExmaReasons( com.webmethods.caf.is.wsclient.campusconnect.work.administration.getexmareasons_wsd_mw1.getExmaReasons getExmaReasons );
  }
