// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 31 12:22:24 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.administration.getexmareasons_wsd_mw1;

public class reason implements java.io.Serializable
  {
  private java.lang.String title;
  private java.lang.String value;

  public java.lang.String getTitle()
    {
    return title;
    }

  public void setTitle( java.lang.String value )
    {
    this.title = value;
    }

  public java.lang.String getValue()
    {
    return value;
    }

  public void setValue( java.lang.String value )
    {
    this.value = value;
    }
  }
