// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Feb 01 16:18:00 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk2;

public interface IsetApplicantInfos_WSD_HK2_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk2.setApplicantInfosResponse setApplicantInfos( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk2.setApplicantInfos setApplicantInfos );
  }
