// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Feb 01 16:18:00 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.setapplicantinfos_wsd_hk2;

public class setApplicantInfosResponse implements java.io.Serializable
  {
  private java.lang.String message;

  public java.lang.String getMessage()
    {
    return message;
    }

  public void setMessage( java.lang.String value )
    {
    this.message = value;
    }
  }
