// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Feb 01 12:30:54 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2;

public class getApplicantInfosResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2.student student = new com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2.student();

public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2.student getStudent()
    {
    return student;
    }

  public void setStudent( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2.student value )
    {
    this.student = value;
    }
  }
