// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Feb 01 12:30:54 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2;

public class getApplicantInfos implements java.io.Serializable
  {
  private java.lang.String applicantId;

  public java.lang.String getApplicantId()
    {
    return applicantId;
    }

  public void setApplicantId( java.lang.String value )
    {
    this.applicantId = value;
    }
  }
