// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Feb 01 12:30:54 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2;

public interface IgetApplicantInfos_WSD_HK2_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2.getApplicantInfosResponse getApplicantInfos( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.getapplicantinfos_wsd_hk2.getApplicantInfos getApplicantInfos );
  }
