/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/


public class ExamregTscs extends com.softwareag.entirex.aci.Tester2 {

	protected void setFields() {
		addField("2  #COURSEID (P9/V)",false,true,4,"scs_output.[V]._courseid");
		addField("2  #DEGREEPROGRAM (A32/V)",false,true,4,"scs_output.[V]._degreeprogram");
		addField("2  #EQUIVALENTID (P2/V)",false,true,4,"scs_output.[V]._equivalentid");
		addField("2  #PROFESSORID (P9/V)",false,true,4,"scs_output.[V]._professorid");
		addField("2  #COURSENAME (A32/V)",false,true,4,"scs_output.[V]._coursename");
		addField("2  #TERM (A32/V)",false,true,4,"scs_output.[V]._term");
		addField("2  #MAXPARTICIPANTS (P9/V)",false,true,4,"scs_output.[V]._maxparticipants");
		addField("2  #COURSEDAY (A32/V)",false,true,4,"scs_output.[V]._courseday");
		addField("2  #COURSETIME (A32/V)",false,true,4,"scs_output.[V]._coursetime");
		addField("2  #COURSEROOM (A32/V)",false,true,4,"scs_output.[V]._courseroom");
		addField("2  #COURSEFINISH (P1/V)",false,true,4,"scs_output.[V]._coursefinish");
		addField("2  #AMOUNTREGISTERED (P9/V)",false,true,4,"scs_output.[V]._amountregistered");
	}

	public static void main(String[] args) {
		new ExamregTscs().test(args, Examreg.class, "scs");
	}
}
