/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/


public class ExamregTsups extends com.softwareag.entirex.aci.Tester2 {

	protected void setFields() {
		addField("2  #PROFID (P9/V)",false,true,4,"sups_output.[V]._profid");
		addField("2  #PFIRSTNAME (A32/V)",false,true,4,"sups_output.[V]._pfirstname");
		addField("2  #PLASTNAME (A32/V)",false,true,4,"sups_output.[V]._plastname");
		addField("2  #PTITEL (A32/V)",false,true,4,"sups_output.[V]._ptitel");
		addField("2  #PCHAIR (A32/V)",false,true,4,"sups_output.[V]._pchair");
		addField("2  #MESSAGE (A40/V)",false,true,4,"sups_output.[V]._message");
	}

	public static void main(String[] args) {
		new ExamregTsups().test(args, Examreg.class, "sups");
	}
}
