// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Jan 23 12:07:48 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.submitgrade_wsd_hk1;

import electric.util.async.Async;

public interface IsubmitGrade_WSD_HK1_PortType
  {
  public void submitGrade( com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.submitgrade_wsd_hk1.StudentsGrade[] submitGrade , Async result );
  }
