// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Fri Jan 24 11:27:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.startscoring_wsd_hk1;

public class startScoring implements java.io.Serializable
  {
  }
