// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Feb 01 12:25:08 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showapplicantlist_wsd_hk1;

public class showApplicantsList implements java.io.Serializable
  {
  }
