// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 20:46:22 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.coursederegistration.loadstudregisteredcourses_wsd;

public class loadStudRegisteredCourses implements java.io.Serializable
  {
  private java.lang.String inputStudId;

  public java.lang.String getInputStudId()
    {
    return inputStudId;
    }

  public void setInputStudId( java.lang.String value )
    {
    this.inputStudId = value;
    }
  }
