/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.060 +0100
 **/

import java.lang.reflect.Method ;
import java.math.BigDecimal;

import com.softwareag.entirex.aci.*;

public class _output {
	private BigDecimal _studentid;
	private String _firstname;
	private String _lastname;
	private String _registereddate;

	public _output() {
	}

	public void set_studentid(BigDecimal _studentid) {
		this._studentid = _studentid;
	}

	public BigDecimal get_studentid() {
		if (this._studentid == null) {
			this._studentid = new BigDecimal(0);
		}
		return this._studentid;
	}

	public void set_firstname(String _firstname) {
		this._firstname = _firstname;
	}

	public String get_firstname() {
		if (this._firstname == null) {
			this._firstname = "";
		}
		return this._firstname;
	}

	public void set_lastname(String _lastname) {
		this._lastname = _lastname;
	}

	public String get_lastname() {
		if (this._lastname == null) {
			this._lastname = "";
		}
		return this._lastname;
	}

	public void set_registereddate(String _registereddate) {
		this._registereddate = _registereddate;
	}

	public String get_registereddate() {
		if (this._registereddate == null) {
			this._registereddate = "";
		}
		return this._registereddate;
	}

	public void add(Marshal marshal) throws BrokerException {
		marshal.addDataN(_studentid, 9, 0);
		marshal.addDataA(_firstname, 32);
		marshal.addDataA(_lastname, 32);
		marshal.addDataA(_registereddate, 10);
	}

	public void get(Marshal marshal) throws BrokerException {
		_studentid = marshal.getDataN(9, 0);
		_firstname = marshal.getDataA(32);
		_lastname = marshal.getDataA(32);
		_registereddate = marshal.getDataA(10);
	}
	public static final Method enterStubMethod = getStubMethod("enterClientStub");
	public static final Method leaveStubMethod = getStubMethod("leaveClientStub");

	private static Method getStubMethod(String name) {
		Method method = null ;
		try {
			method = RPCService.class.getMethod(name , null ) ;
		} catch ( Exception ex ) {}
		return method ;
	}
	private void enterStub() {
		if ( enterStubMethod != null ) {
			try {
				enterStubMethod.invoke ( this , null ) ;
			} catch ( Exception ex ) {} 
		}
	}
	private void leaveStub() {
		if ( leaveStubMethod != null ) {
			try {
				leaveStubMethod.invoke ( this , null ) ;
			} catch ( Exception ex ) {}
		}
	}
}
