/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/


public class ExamregTsusi extends com.softwareag.entirex.aci.Tester2 {

	protected void setFields() {
		addField("1  #STUDENTID (P9)",true,false,1,"1");
		addField("1  #FIRSTNAME (A32)",false,true,4,"susi_firstname");
		addField("1  #LASTNAME (A32)",false,true,4,"susi_lastname");
		addField("1  #ADDRESSLINE1 (A32)",false,true,4,"susi_addressline1");
		addField("1  #ADDRESSLINE2 (A32)",false,true,4,"susi_addressline2");
		addField("1  #DEGREEPROGRAM (A32)",false,true,4,"susi_degreeprogram");
		addField("1  #EMAIL (A32)",false,true,4,"susi_email");
		addField("1  #PHONE (A32)",false,true,4,"susi_phone");
		addField("1  #DOB (A10)",false,true,4,"susi_dob");
		addField("1  #TERM (P3)",false,true,4,"susi_term");
		addField("1  #REGISTERED (A10)",false,true,4,"susi_registered");
		addField("1  #ACTIVE (P1)",false,true,4,"susi_active");
		addField("1  #MESSAGE (A40)",false,true,4,"susi_message");
	}

	public static void main(String[] args) {
		new ExamregTsusi().test(args, Examreg.class, "susi");
	}
}
