/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/

import java.lang.reflect.Method ;
import java.math.BigDecimal;

import com.softwareag.entirex.aci.*;

public class Sups_output {
	private BigDecimal _profid;
	private String _pfirstname;
	private String _plastname;
	private String _ptitel;
	private String _pchair;
	private String _message;

	public Sups_output() {
	}

	public void set_profid(BigDecimal _profid) {
		this._profid = _profid;
	}

	public BigDecimal get_profid() {
		if (this._profid == null) {
			this._profid = new BigDecimal(0);
		}
		return this._profid;
	}

	public void set_pfirstname(String _pfirstname) {
		this._pfirstname = _pfirstname;
	}

	public String get_pfirstname() {
		if (this._pfirstname == null) {
			this._pfirstname = "";
		}
		return this._pfirstname;
	}

	public void set_plastname(String _plastname) {
		this._plastname = _plastname;
	}

	public String get_plastname() {
		if (this._plastname == null) {
			this._plastname = "";
		}
		return this._plastname;
	}

	public void set_ptitel(String _ptitel) {
		this._ptitel = _ptitel;
	}

	public String get_ptitel() {
		if (this._ptitel == null) {
			this._ptitel = "";
		}
		return this._ptitel;
	}

	public void set_pchair(String _pchair) {
		this._pchair = _pchair;
	}

	public String get_pchair() {
		if (this._pchair == null) {
			this._pchair = "";
		}
		return this._pchair;
	}

	public void set_message(String _message) {
		this._message = _message;
	}

	public String get_message() {
		if (this._message == null) {
			this._message = "";
		}
		return this._message;
	}

	public void add(Marshal marshal) throws BrokerException {
		marshal.addDataN(_profid, 9, 0);
		marshal.addDataA(_pfirstname, 32);
		marshal.addDataA(_plastname, 32);
		marshal.addDataA(_ptitel, 32);
		marshal.addDataA(_pchair, 32);
		marshal.addDataA(_message, 40);
	}

	public void get(Marshal marshal) throws BrokerException {
		_profid = marshal.getDataN(9, 0);
		_pfirstname = marshal.getDataA(32);
		_plastname = marshal.getDataA(32);
		_ptitel = marshal.getDataA(32);
		_pchair = marshal.getDataA(32);
		_message = marshal.getDataA(40);
	}
	public static final Method enterStubMethod = getStubMethod("enterClientStub");
	public static final Method leaveStubMethod = getStubMethod("leaveClientStub");

	private static Method getStubMethod(String name) {
		Method method = null ;
		try {
			method = RPCService.class.getMethod(name , null ) ;
		} catch ( Exception ex ) {}
		return method ;
	}
	private void enterStub() {
		if ( enterStubMethod != null ) {
			try {
				enterStubMethod.invoke ( this , null ) ;
			} catch ( Exception ex ) {} 
		}
	}
	private void leaveStub() {
		if ( leaveStubMethod != null ) {
			try {
				leaveStubMethod.invoke ( this , null ) ;
			} catch ( Exception ex ) {}
		}
	}
}
