// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 00:10:32 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1;

public class fCL implements java.io.Serializable
  {
  private java.math.BigDecimal _COURSEID;
  private java.lang.String _DEGREEPROGRAM;
  private java.math.BigDecimal _EQUIVALENTID;
  private java.math.BigDecimal _PROFESSORID;
  private java.lang.String _COURSENAME;
  private java.lang.String _TERM;
  private java.math.BigDecimal _MAXPARTICIPANTS;
  private java.lang.String _COURSEDAY;
  private java.lang.String _COURSETIME;
  private java.lang.String _COURSEROOM;
  private java.math.BigDecimal _COURSEFINISH;
  private java.math.BigDecimal _AMOUNTREGISTERED;
  private java.lang.String _PLASTNAME;
  private java.lang.String _PFIRSTNAME;
  private java.lang.String _PTITEL;
  private java.lang.String _PCHAIR;

  public java.math.BigDecimal get_COURSEID()
    {
    return _COURSEID;
    }

  public void set_COURSEID( java.math.BigDecimal value )
    {
    this._COURSEID = value;
    }

  public java.lang.String get_DEGREEPROGRAM()
    {
    return _DEGREEPROGRAM;
    }

  public void set_DEGREEPROGRAM( java.lang.String value )
    {
    this._DEGREEPROGRAM = value;
    }

  public java.math.BigDecimal get_EQUIVALENTID()
    {
    return _EQUIVALENTID;
    }

  public void set_EQUIVALENTID( java.math.BigDecimal value )
    {
    this._EQUIVALENTID = value;
    }

  public java.math.BigDecimal get_PROFESSORID()
    {
    return _PROFESSORID;
    }

  public void set_PROFESSORID( java.math.BigDecimal value )
    {
    this._PROFESSORID = value;
    }

  public java.lang.String get_COURSENAME()
    {
    return _COURSENAME;
    }

  public void set_COURSENAME( java.lang.String value )
    {
    this._COURSENAME = value;
    }

  public java.lang.String get_TERM()
    {
    return _TERM;
    }

  public void set_TERM( java.lang.String value )
    {
    this._TERM = value;
    }

  public java.math.BigDecimal get_MAXPARTICIPANTS()
    {
    return _MAXPARTICIPANTS;
    }

  public void set_MAXPARTICIPANTS( java.math.BigDecimal value )
    {
    this._MAXPARTICIPANTS = value;
    }

  public java.lang.String get_COURSEDAY()
    {
    return _COURSEDAY;
    }

  public void set_COURSEDAY( java.lang.String value )
    {
    this._COURSEDAY = value;
    }

  public java.lang.String get_COURSETIME()
    {
    return _COURSETIME;
    }

  public void set_COURSETIME( java.lang.String value )
    {
    this._COURSETIME = value;
    }

  public java.lang.String get_COURSEROOM()
    {
    return _COURSEROOM;
    }

  public void set_COURSEROOM( java.lang.String value )
    {
    this._COURSEROOM = value;
    }

  public java.math.BigDecimal get_COURSEFINISH()
    {
    return _COURSEFINISH;
    }

  public void set_COURSEFINISH( java.math.BigDecimal value )
    {
    this._COURSEFINISH = value;
    }

  public java.math.BigDecimal get_AMOUNTREGISTERED()
    {
    return _AMOUNTREGISTERED;
    }

  public void set_AMOUNTREGISTERED( java.math.BigDecimal value )
    {
    this._AMOUNTREGISTERED = value;
    }

  public java.lang.String get_PLASTNAME()
    {
    return _PLASTNAME;
    }

  public void set_PLASTNAME( java.lang.String value )
    {
    this._PLASTNAME = value;
    }

  public java.lang.String get_PFIRSTNAME()
    {
    return _PFIRSTNAME;
    }

  public void set_PFIRSTNAME( java.lang.String value )
    {
    this._PFIRSTNAME = value;
    }

  public java.lang.String get_PTITEL()
    {
    return _PTITEL;
    }

  public void set_PTITEL( java.lang.String value )
    {
    this._PTITEL = value;
    }

  public java.lang.String get_PCHAIR()
    {
    return _PCHAIR;
    }

  public void set_PCHAIR( java.lang.String value )
    {
    this._PCHAIR = value;
    }
  }
