// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 00:10:32 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1;

public interface IloadFilteredCourses_WSD_HK1_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1.loadFilteredCoursesOutput loadFilteredCourses( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1.loadFilteredCoursesInput loadFilteredCoursesInput );
  }
