// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:54:23 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1;

public class loadFilteredCoursesOutput implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1.fCL[] outputCourses;
  private java.lang.String hidden;

  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1.fCL[] getOutputCourses()
    {
    return outputCourses;
    }

  public void setOutputCourses( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1.fCL[] value )
    {
    this.outputCourses = value;
    }

  public java.lang.String getHidden()
    {
    return hidden;
    }

  public void setHidden( java.lang.String value )
    {
    this.hidden = value;
    }
  }
