// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 00:10:32 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1;

public class loadFilteredCoursesOutput implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1.fCL[] outputCourses;

  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1.fCL[] getOutputCourses()
    {
    return outputCourses;
    }

  public void setOutputCourses( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1.fCL[] value )
    {
    this.outputCourses = value;
    }
  }
