// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 00:10:32 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class loadFilteredCourses_WSD_HK1Helper
  {
  public static IloadFilteredCourses_WSD_HK1_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/courseregistration/loadfilteredcourses_wsd_hk1/loadFilteredCourses_WSD_HK1.wsdl" );
    }

  public static IloadFilteredCourses_WSD_HK1_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IloadFilteredCourses_WSD_HK1_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IloadFilteredCourses_WSD_HK1_PortType) Registry.bind( url, IloadFilteredCourses_WSD_HK1_PortType.class, context );
    }
  }
