// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 12 00:10:32 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1;

public class loadFilteredCoursesInput implements java.io.Serializable
  {
  private java.math.BigDecimal studId;

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }
  }
