// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Jan 28 20:54:23 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd_hk1;

public class loadFilteredCoursesInput implements java.io.Serializable
  {
  private java.math.BigDecimal studId;
  private java.lang.String hidden;

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }

  public java.lang.String getHidden()
    {
    return hidden;
    }

  public void setHidden( java.lang.String value )
    {
    this.hidden = value;
    }
  }
