// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Dec 28 06:52:14 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd;

public interface IloadFilteredCourses_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd.fCL[] loadFilteredCourses( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd.loadFilteredCoursesInput loadFilteredCoursesInput );
  }
