// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Dec 28 06:52:14 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class loadFilteredCourses_WSDHelper
  {
  public static IloadFilteredCourses_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/work/src/com/webmethods/caf/is/wsclient/campusconnect/work/courseregistration/loadfilteredcourses_wsd/loadFilteredCourses_WSD.wsdl" );
    }

  public static IloadFilteredCourses_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IloadFilteredCourses_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IloadFilteredCourses_WSD_PortType) Registry.bind( url, IloadFilteredCourses_WSD_PortType.class, context );
    }
  }
