// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Jan 11 16:16:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.new_wsd111111111111111;

public class course implements java.io.Serializable
  {
  private java.lang.String _DEGREEPROGRAM;
  private java.lang.String _EQUIVALENTID;
  private java.lang.String _PROFESSORID;
  private java.lang.String _COURSENAME;
  private java.lang.String _TERM;
  private java.lang.String _MAXPARTICIPANTS;
  private java.lang.String _COURSEDAY;
  private java.lang.String _COURSETIME;
  private java.lang.String _COURSEROOM;
  private java.lang.String _COURSEFINISH;
  private java.lang.String _AMOUNTREGISTERED;
  private java.lang.String _COURSEID;

  public java.lang.String get_DEGREEPROGRAM()
    {
    return _DEGREEPROGRAM;
    }

  public void set_DEGREEPROGRAM( java.lang.String value )
    {
    this._DEGREEPROGRAM = value;
    }

  public java.lang.String get_EQUIVALENTID()
    {
    return _EQUIVALENTID;
    }

  public void set_EQUIVALENTID( java.lang.String value )
    {
    this._EQUIVALENTID = value;
    }

  public java.lang.String get_PROFESSORID()
    {
    return _PROFESSORID;
    }

  public void set_PROFESSORID( java.lang.String value )
    {
    this._PROFESSORID = value;
    }

  public java.lang.String get_COURSENAME()
    {
    return _COURSENAME;
    }

  public void set_COURSENAME( java.lang.String value )
    {
    this._COURSENAME = value;
    }

  public java.lang.String get_TERM()
    {
    return _TERM;
    }

  public void set_TERM( java.lang.String value )
    {
    this._TERM = value;
    }

  public java.lang.String get_MAXPARTICIPANTS()
    {
    return _MAXPARTICIPANTS;
    }

  public void set_MAXPARTICIPANTS( java.lang.String value )
    {
    this._MAXPARTICIPANTS = value;
    }

  public java.lang.String get_COURSEDAY()
    {
    return _COURSEDAY;
    }

  public void set_COURSEDAY( java.lang.String value )
    {
    this._COURSEDAY = value;
    }

  public java.lang.String get_COURSETIME()
    {
    return _COURSETIME;
    }

  public void set_COURSETIME( java.lang.String value )
    {
    this._COURSETIME = value;
    }

  public java.lang.String get_COURSEROOM()
    {
    return _COURSEROOM;
    }

  public void set_COURSEROOM( java.lang.String value )
    {
    this._COURSEROOM = value;
    }

  public java.lang.String get_COURSEFINISH()
    {
    return _COURSEFINISH;
    }

  public void set_COURSEFINISH( java.lang.String value )
    {
    this._COURSEFINISH = value;
    }

  public java.lang.String get_AMOUNTREGISTERED()
    {
    return _AMOUNTREGISTERED;
    }

  public void set_AMOUNTREGISTERED( java.lang.String value )
    {
    this._AMOUNTREGISTERED = value;
    }

  public java.lang.String get_COURSEID()
    {
    return _COURSEID;
    }

  public void set_COURSEID( java.lang.String value )
    {
    this._COURSEID = value;
    }
  }
