// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Jan 11 16:16:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.new_wsd111111111111111;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class new_wsd111111111111111Helper
  {
  public static Inew_wsd111111111111111_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/Support/src/com/webmethods/caf/is/wsclient/campusconnect/work/searchcourse/new_wsd111111111111111/new_wsd111111111111111.wsdl" );
    }

  public static Inew_wsd111111111111111_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static Inew_wsd111111111111111_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (Inew_wsd111111111111111_PortType) Registry.bind( url, Inew_wsd111111111111111_PortType.class, context );
    }
  }
