// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Jan 11 16:16:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.new_wsd111111111111111;

public class searchCourse implements java.io.Serializable
  {
  private java.lang.String searchString;

  public java.lang.String getSearchString()
    {
    return searchString;
    }

  public void setSearchString( java.lang.String value )
    {
    this.searchString = value;
    }
  }
