// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Jan 11 16:16:56 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.new_wsd111111111111111;

public class searchCourseResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.new_wsd111111111111111.course[] courses;

  public com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.new_wsd111111111111111.course[] getCourses()
    {
    return courses;
    }

  public void setCourses( com.webmethods.caf.is.wsclient.campusconnect.work.searchcourse.new_wsd111111111111111.course[] value )
    {
    this.courses = value;
    }
  }
