// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Dec 26 05:26:45 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class showPersonalData_WSDHelper
  {
  public static IshowPersonalData_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Documents and Settings/wir09cdz/workspace82/CampusConnect/src/com/webmethods/caf/is/wsclient/campusconnect/work/personaldata/showpersonaldata_wsd/showPersonalData_WSD.wsdl" );
    }

  public static IshowPersonalData_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IshowPersonalData_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IshowPersonalData_WSD_PortType) Registry.bind( url, IshowPersonalData_WSD_PortType.class, context );
    }
  }
