// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Dec 26 05:26:45 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.personaldata.showpersonaldata_wsd;

public class student implements java.io.Serializable
  {
  private java.lang.String studentid;
  private java.lang.String firstname;
  private java.lang.String lastname;
  private java.lang.String registered;
  private java.lang.String term;
  private java.lang.String degreeprogram;
  private java.lang.String dob;
  private java.lang.String adressline1;
  private java.lang.String adressline2;

  public java.lang.String getStudentid()
    {
    return studentid;
    }

  public void setStudentid( java.lang.String value )
    {
    this.studentid = value;
    }

  public java.lang.String getFirstname()
    {
    return firstname;
    }

  public void setFirstname( java.lang.String value )
    {
    this.firstname = value;
    }

  public java.lang.String getLastname()
    {
    return lastname;
    }

  public void setLastname( java.lang.String value )
    {
    this.lastname = value;
    }

  public java.lang.String getRegistered()
    {
    return registered;
    }

  public void setRegistered( java.lang.String value )
    {
    this.registered = value;
    }

  public java.lang.String getTerm()
    {
    return term;
    }

  public void setTerm( java.lang.String value )
    {
    this.term = value;
    }

  public java.lang.String getDegreeprogram()
    {
    return degreeprogram;
    }

  public void setDegreeprogram( java.lang.String value )
    {
    this.degreeprogram = value;
    }

  public java.lang.String getDob()
    {
    return dob;
    }

  public void setDob( java.lang.String value )
    {
    this.dob = value;
    }

  public java.lang.String getAdressline1()
    {
    return adressline1;
    }

  public void setAdressline1( java.lang.String value )
    {
    this.adressline1 = value;
    }

  public java.lang.String getAdressline2()
    {
    return adressline2;
    }

  public void setAdressline2( java.lang.String value )
    {
    this.adressline2 = value;
    }
  }
