// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:51:38 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.setstudactive_wsd;

public interface IsetStudActive_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.setstudactive_wsd.setStudActiveResponse setStudActive( com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.setstudactive_wsd.setStudActive setStudActive );
  }
