// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Jan 23 22:00:31 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showenrolledstuds_wsd;

public interface IshowEnrolledStuds_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showenrolledstuds_wsd.studDetails[] showEnrolledStuds( com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showenrolledstuds_wsd.showEnrolledStuds showEnrolledStuds );
  }
