// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Jan 23 22:00:31 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.enrollment.showenrolledstuds_wsd;

public class studDetails implements java.io.Serializable
  {
  private java.lang.String studId;
  private java.lang.String firstName;
  private java.lang.String lastName;
  private java.lang.String degreeProgram;
  private java.lang.String registered;
  private java.lang.String active;

  public java.lang.String getStudId()
    {
    return studId;
    }

  public void setStudId( java.lang.String value )
    {
    this.studId = value;
    }

  public java.lang.String getFirstName()
    {
    return firstName;
    }

  public void setFirstName( java.lang.String value )
    {
    this.firstName = value;
    }

  public java.lang.String getLastName()
    {
    return lastName;
    }

  public void setLastName( java.lang.String value )
    {
    this.lastName = value;
    }

  public java.lang.String getDegreeProgram()
    {
    return degreeProgram;
    }

  public void setDegreeProgram( java.lang.String value )
    {
    this.degreeProgram = value;
    }

  public java.lang.String getRegistered()
    {
    return registered;
    }

  public void setRegistered( java.lang.String value )
    {
    this.registered = value;
    }

  public java.lang.String getActive()
    {
    return active;
    }

  public void setActive( java.lang.String value )
    {
    this.active = value;
    }
  }
