/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file EXAMREG.refactored.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 8.2.2.0.186, Date: 04 Nov 2011 (1.132.4.9)
 ** Generated: 2013-11-17 20:31:09.076 +0100
 **/


public class ExamregTses extends com.softwareag.entirex.aci.Tester2 {

	protected void setFields() {
		addField("2  #EXAMID (P9/V)",false,true,4,"ses_output.[V]._examid");
		addField("2  #COURSEID (P9/V)",false,true,4,"ses_output.[V]._courseid");
		addField("2  #COURSENAME (A32/V)",false,true,4,"ses_output.[V]._coursename");
		addField("2  #PROFESSORID (P9/V)",false,true,4,"ses_output.[V]._professorid");
		addField("2  #PROFESSORLASTNAME (A32/V)",false,true,4,"ses_output.[V]._professorlastname");
		addField("2  #AMOUNTREGISTERED (P9/V)",false,true,4,"ses_output.[V]._amountregistered");
		addField("2  #MAXPARTICIPANTS (P9/V)",false,true,4,"ses_output.[V]._maxparticipants");
		addField("2  #EXAMDATE (A32/V)",false,true,4,"ses_output.[V]._examdate");
		addField("2  #EXAMTIME (A32/V)",false,true,4,"ses_output.[V]._examtime");
		addField("2  #EXAMROOM (A32/V)",false,true,4,"ses_output.[V]._examroom");
	}

	public static void main(String[] args) {
		new ExamregTses().test(args, Examreg.class, "ses");
	}
}
