// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:43:44 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.savestudinfos_wsd;

public class saveStudInfos implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.savestudinfos_wsd.studDetails studDetails = new com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.savestudinfos_wsd.studDetails();

public com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.savestudinfos_wsd.studDetails getStudDetails()
    {
    return studDetails;
    }

  public void setStudDetails( com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.savestudinfos_wsd.studDetails value )
    {
    this.studDetails = value;
    }
  }
