// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:51:38 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.setstudactive_wsd;

public class setStudActive implements java.io.Serializable
  {
  private java.math.BigDecimal studId;
  private java.math.BigDecimal activeStatus;

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }

  public java.math.BigDecimal getActiveStatus()
    {
    return activeStatus;
    }

  public void setActiveStatus( java.math.BigDecimal value )
    {
    this.activeStatus = value;
    }
  }
