// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Dec 25 21:51:38 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.enrolment.setstudactive_wsd;

public class setStudActiveResponse implements java.io.Serializable
  {
  private java.lang.String outputMessage;

  public java.lang.String getOutputMessage()
    {
    return outputMessage;
    }

  public void setOutputMessage( java.lang.String value )
    {
    this.outputMessage = value;
    }
  }
