// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Thu Jan 30 20:49:54 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.submitgrade_wsd_hk2;

import electric.util.async.Async;

public interface IsubmitGrade_WSD_HK2_PortType
  {
  public void submitGrade( com.webmethods.caf.is.wsclient.campusconnect.work.gradesubmission.submitgrade_wsd_hk2.submitGrade submitGrade , Async result );
  }
