// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 11:31:39 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd;

public class showPersonalDataStud implements java.io.Serializable
  {
  private java.math.BigDecimal studId;

  public java.math.BigDecimal getStudId()
    {
    return studId;
    }

  public void setStudId( java.math.BigDecimal value )
    {
    this.studId = value;
    }
  }
