// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sun Jan 26 11:31:39 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd;

public class showPersonalDataStudResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd.studInfo studInfo = new com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd.studInfo();

public com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd.studInfo getStudInfo()
    {
    return studInfo;
    }

  public void setStudInfo( com.webmethods.caf.is.wsclient.campusconnect.work.editpersonaldatastud.showpersonaldatastud_wsd.studInfo value )
    {
    this.studInfo = value;
    }
  }
