// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Tue Dec 24 01:38:27 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.loadfilteredcourses_wsd;

public class fCL implements java.io.Serializable
  {
  private java.lang.String courseId;
  private java.lang.String courseName;
  private java.lang.String maxParticipants;
  private java.lang.String profId;
  private java.lang.String profFirstName;
  private java.lang.String profLastName;
  private java.lang.String profTitle;
  private java.lang.String degreeProgram;

  public java.lang.String getCourseId()
    {
    return courseId;
    }

  public void setCourseId( java.lang.String value )
    {
    this.courseId = value;
    }

  public java.lang.String getCourseName()
    {
    return courseName;
    }

  public void setCourseName( java.lang.String value )
    {
    this.courseName = value;
    }

  public java.lang.String getMaxParticipants()
    {
    return maxParticipants;
    }

  public void setMaxParticipants( java.lang.String value )
    {
    this.maxParticipants = value;
    }

  public java.lang.String getProfId()
    {
    return profId;
    }

  public void setProfId( java.lang.String value )
    {
    this.profId = value;
    }

  public java.lang.String getProfFirstName()
    {
    return profFirstName;
    }

  public void setProfFirstName( java.lang.String value )
    {
    this.profFirstName = value;
    }

  public java.lang.String getProfLastName()
    {
    return profLastName;
    }

  public void setProfLastName( java.lang.String value )
    {
    this.profLastName = value;
    }

  public java.lang.String getProfTitle()
    {
    return profTitle;
    }

  public void setProfTitle( java.lang.String value )
    {
    this.profTitle = value;
    }

  public java.lang.String getDegreeProgram()
    {
    return degreeProgram;
    }

  public void setDegreeProgram( java.lang.String value )
    {
    this.degreeProgram = value;
    }
  }
