// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 22 11:43:32 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1;

public class getCourseDetails implements java.io.Serializable
  {
  private java.lang.String id;

  public java.lang.String getId()
    {
    return id;
    }

  public void setId( java.lang.String value )
    {
    this.id = value;
    }
  }
