// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Wed Jan 22 11:43:32 CET 2014

package com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1;

public class getCourseDetailsResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1.course course = new com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1.course();

public com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1.course getCourse()
    {
    return course;
    }

  public void setCourse( com.webmethods.caf.is.wsclient.campusconnect.utils.courses.getcoursedetails_wsd_hk1.course value )
    {
    this.course = value;
    }
  }
