// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Dec 28 06:40:00 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd;

public interface IregisterCourses_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd.registeredCourses[] registerCourses( com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd.registerCoursesInput registerCoursesInput );
  }
