// generated by Glue 8.0 Fix 4 build 5 (wsdl2java) on Sat Dec 28 06:40:00 CET 2013

package com.webmethods.caf.is.wsclient.campusconnect.work.courseregistration.registercourses_wsd;

public class registeredCourses implements java.io.Serializable
  {
  private java.lang.String courseId;
  private java.lang.String courseName;

  public java.lang.String getCourseId()
    {
    return courseId;
    }

  public void setCourseId( java.lang.String value )
    {
    this.courseId = value;
    }

  public java.lang.String getCourseName()
    {
    return courseName;
    }

  public void setCourseName( java.lang.String value )
    {
    this.courseName = value;
    }
  }
